### ISSUE TITLE
Usage in AccessibilityService

### ISSUE THREAD

**Issue by NoHarmDan** [sensorberg-dev/EasyIPC#3]
Hi, are you still working on this?

I really do like the library, but I fail to figure out a way to use it with an `AccessibilityService` - I need to send events from an `AccessibilityService` to a different `Service`, running in a separate process. Since `AccessibilityService` uses a specific `IBinder` (which I cannot and naturally don't want to change), I cannot very well use the `IpcServiceHelper`. And `IpcActivityHelper` would try to bind the `Service` to the given `Context` via the provided `Intent`, which I don't want either - the `Service` is already running as a foreground service, no need to bind or start anything, I just need to know that the `AccessibilityService` detected something relevant to it. Frankly, I don't know a lot about AIDL and how the binding and stuff works, so maybe what I'm asking isn't even possible or it's obvious and I'm just dumb.

And btw, you say if we cannot override the `IpcService`, to simply copy the contents. That doesn't work since `IpcBase.clearAll()` is not public and therefore cannot be called from outside the package.

**Comment by budius** [comment]
Good morning @NoHarmDan ,

This was planned as a Activtiy-to-Service communication and I never tried as a Service-to-Service option.
I did a quick look-up on the `AccessibilityService` and it seems the `onBind` method is final, and only the Android framework is supposed to bind to it. That means, I really don't think that make a AccessibilityService-to-Service connection via binders is possible

But I'll suggest a different approach to your issue. You mention you "just need to know that the AccessibilityService detected something relevant to it".
So maybe you want to pass those messages via Intents. Something like this:

```
MyAccessibilityService extends AccessibilityService {

     private void myDataProcessing() {
          if(detect something relevant to the other service) {
                Intent messageToOtherService = Intent(this, MyOtherService.class);
                messageToOtherService.setAction("I got something for you")
                messageToOtherService.putExtra("extras"  ... add here any info you need to send)
                startService(messageToOtherService)
          }
     }
}
```
and to receive the message:
```
MyOtherService extends Service {
       public int onStartCommand(Intent intent, int flags, int startId) {
              if(intent.getAction() == "I got something for you") {
                      handleMessageFromAccessibilityService(intent)
              }
       }

     private void handleMessageFromAccessibilityService(Intent intent) {
          ....  check here your data
     }
 
}
```

Similarly you could do with `BroadcastReceiver` registered inside the service between `Service.onCreate` and `Service.onDestroy`

**Comment by NoHarmDan** [comment]
Thanks for the reply, tbh despite years of experience in Android development, I never needed to use service binding, so I don't really know a lot about it. If it can't be used for service-to-service communication, I'll have to look elsewhere.

The suggested approach won't work in a case where the other service is already running, since as far as I know broadcast processing is serial and can potentially be slowed down by the system, which means the other service might not get it fast enough or maybe even not at all. But I've looked into another alternative, IPC event buses, and that shows promise.
